# Generated by Django 6.0.4 on 2026-05-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_number', models.IntegerField()),
                ('measure_label_1', models.CharField(default='Medida 1', max_length=60)),
                ('measure_1', models.CharField(max_length=30)),
                ('measure_label_2', models.CharField(blank=True, default='', max_length=60)),
                ('measure_2', models.CharField(blank=True, max_length=30)),
                ('measure_label_3', models.CharField(blank=True, default='', max_length=60)),
                ('measure_3', models.CharField(blank=True, max_length=30)),
                ('result', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No Conforme')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('process_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensional_logs', to='production.processrecord')),
            ],
            options={
                'ordering': ['process_record', 'piece_number'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T5', 'T5')], max_length=4)),
                ('client', models.CharField(max_length=200)),
                ('item_tramo', models.CharField(max_length=200)),
                ('moto', models.CharField(max_length=200)),
                ('dimensions_ok', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('otras', 'Otras')], max_length=10)),
                ('sheet_type', models.CharField(choices=[('cr', 'CR'), ('gv', 'GV'), ('hr', 'HR'), ('cr_est', 'CR EST'), ('hr_est', 'HR EST'), ('otras', 'Otras')], max_length=10)),
                ('appearance_ok', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=5)),
                ('saw_type_ref', models.CharField(blank=True, default='NA', max_length=100)),
                ('rpm_ref', models.CharField(blank=True, default='NA', max_length=50)),
                ('jaw_pressure', models.CharField(choices=[('verificado', 'Verificado'), ('no_aplica', 'No Aplica')], max_length=20)),
                ('cut_appearance', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No Conforme')], max_length=20)),
                ('knurling_distance', models.CharField(blank=True, default='NA', max_length=100)),
                ('double_knurling_free', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No Conforme'), ('no_aplica', 'No Aplica')], max_length=20)),
                ('sample_1', models.CharField(max_length=50)),
                ('sample_2', models.CharField(max_length=50)),
                ('sample_3', models.CharField(max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('process_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check', to='production.processrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
