# Generated by Django 4.2.30 on 2026-06-29 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_remove_producttype_rpm_remove_producttype_saw_type_and_more'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='shift_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_check', to='production.processshiftentry'),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='process_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.processrecord'),
        ),
    ]
