# Generated by Django 6.0.4 on 2026-05-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cut_length', models.FloatField(verbose_name='Longitud de corte (mm)')),
                ('client', models.CharField(blank=True, max_length=200)),
                ('default_priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('requires_chaflan', models.BooleanField(default=False)),
                ('requires_moleteo', models.BooleanField(default=False)),
                ('requires_curvado', models.BooleanField(default=False)),
                ('saw_type', models.CharField(choices=[('hss', 'HSS'), ('tct', 'TCT'), ('none', 'Ninguno')], default='none', max_length=4)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('process_type', models.CharField(choices=[('corte', 'Corte'), ('chaflan', 'Chaflanado'), ('moleteo', 'Moleteado'), ('curvado', 'Curvado')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('operators', models.ManyToManyField(blank=True, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('total_quantity', models.IntegerField()),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_basket', 'En canasta'), ('in_process', 'En proceso'), ('finished', 'Terminado'), ('dispatched', 'Despachado')], default='in_basket', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to=settings.AUTH_USER_MODEL)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.producttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TubeSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('round', 'Redondo'), ('square', 'Cuadrado')], max_length=10)),
                ('outer_diameter', models.FloatField(verbose_name='Diámetro/lado (mm)')),
                ('thickness', models.FloatField(verbose_name='Espesor (mm)')),
                ('material', models.CharField(choices=[('cr', 'CR'), ('hr', 'HR'), ('cr_est', 'CR EST'), ('hr_est', 'HR EST')], max_length=10)),
                ('original_length', models.FloatField(default=6000, verbose_name='Longitud original (mm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['outer_diameter', 'thickness'],
                'unique_together': {('outer_diameter', 'thickness', 'material', 'original_length')},
            },
        ),
        migrations.AddField(
            model_name='producttype',
            name='tube_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_types', to='production.tubespec'),
        ),
        migrations.CreateModel(
            name='ProcessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(max_length=10)),
                ('sequence', models.IntegerField(default=1)),
                ('shift', models.CharField(blank=True, choices=[('A', 'Turno A (06:00–14:00)'), ('B', 'Turno B (14:00–22:00)'), ('C', 'Turno C (22:00–06:00)')], max_length=1)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_process', 'En proceso'), ('finished', 'Terminado')], default='pending', max_length=20)),
                ('qty_assigned', models.IntegerField()),
                ('qty_done', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_records', to='production.machine')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_records', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='production.productionbatch')),
            ],
            options={
                'ordering': ['batch', 'sequence'],
                'unique_together': {('batch', 'process_type')},
            },
        ),
    ]
