# Generated by Django 4.2.30 on 2026-05-03 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mes del programa')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('closed', 'Cerrado')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', '-version'],
            },
        ),
        migrations.CreateModel(
            name='CuttingProgramLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.IntegerField(verbose_name='Día inicio')),
                ('end_day', models.IntegerField(verbose_name='Día final')),
                ('pieces_per_hour', models.FloatField(blank=True, null=True, verbose_name='Piezas/hora')),
                ('item_code', models.CharField(blank=True, max_length=50, verbose_name='Item')),
                ('tube_description', models.CharField(max_length=300, verbose_name='Descripción tramo cortado')),
                ('pedido_quantity', models.IntegerField(verbose_name='Cantidad pedida (cliente)')),
                ('total_quantity', models.IntegerField(verbose_name='Total a cortar')),
                ('demo_pieces', models.IntegerField(default=0, verbose_name='Piezas demo')),
                ('tube_count', models.IntegerField(blank=True, null=True, verbose_name='Tramos tubo (cantidad)')),
                ('tube_length_mm', models.FloatField(blank=True, null=True, verbose_name='Tubo largo (mm)')),
                ('saw_type', models.CharField(choices=[('hss', 'HSS'), ('tct', 'TCT')], max_length=5, verbose_name='Tipo sierra')),
                ('saw_teeth', models.IntegerField(blank=True, null=True, verbose_name='Número de dientes')),
                ('rpm', models.IntegerField(blank=True, null=True, verbose_name='RPM')),
                ('advance_high', models.FloatField(blank=True, null=True, verbose_name='Avance High')),
                ('advance_low', models.FloatField(blank=True, null=True, verbose_name='Avance Low')),
                ('client', models.CharField(max_length=200, verbose_name='Cliente')),
                ('packaging', models.CharField(blank=True, max_length=100, verbose_name='Embalaje')),
                ('notes', models.TextField(blank=True)),
                ('batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_line', to='production.productionbatch')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_lines', to='production.producttype')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.cuttingprogram')),
            ],
            options={
                'ordering': ['program', 'id'],
            },
        ),
    ]
