# Generated by Django 4.2.30 on 2026-05-04 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_cuttingprogram_cuttingprogramline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_process', 'En proceso'), ('paused', 'Pausado (turno cerrado)'), ('finished', 'Terminado')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcessShiftEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, choices=[('A', 'Turno A (06:00–14:00)'), ('B', 'Turno B (14:00–22:00)'), ('C', 'Turno C (22:00–06:00)')], max_length=1)),
                ('qty_done', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_entries', to='production.machine')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_entries', to=settings.AUTH_USER_MODEL)),
                ('process_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_entries', to='production.processrecord')),
            ],
            options={
                'ordering': ['process_record', 'started_at'],
            },
        ),
    ]
