# Generated by Django 4.2.30 on 2026-05-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_processrecord_status_processshiftentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingprogramline',
            name='demo_pieces',
        ),
        migrations.RemoveField(
            model_name='cuttingprogramline',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='cuttingprogramline',
            name='start_day',
        ),
        migrations.AddField(
            model_name='cuttingprogramline',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha final'),
        ),
        migrations.AddField(
            model_name='cuttingprogramline',
            name='sections_per_tube',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tramos por tubo'),
        ),
        migrations.AddField(
            model_name='cuttingprogramline',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='cuttingprogramline',
            name='pedido_quantity',
            field=models.IntegerField(verbose_name='Cantidad pedida (piezas)'),
        ),
        migrations.AlterField(
            model_name='cuttingprogramline',
            name='total_quantity',
            field=models.IntegerField(verbose_name='Total a cortar (piezas)'),
        ),
        migrations.AlterField(
            model_name='cuttingprogramline',
            name='tube_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tubos largos (cantidad)'),
        ),
        migrations.AlterField(
            model_name='tubespec',
            name='outer_diameter',
            field=models.CharField(max_length=20, verbose_name='Diámetro/lado (mm)'),
        ),
    ]
