# Generated by Django 4.2.30 on 2026-06-18 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0004_remove_cuttingprogramline_demo_pieces_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TubeReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de tubos recibidos')),
                ('delivered_by', models.CharField(blank=True, max_length=200, verbose_name='Entregado por (almacén)')),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tube_receptions', to=settings.AUTH_USER_MODEL)),
                ('tube_spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='production.tubespec')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
