# Generated by Django 4.2.30 on 2026-06-18 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_tubereception'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubereception',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_receptions', to='production.productionbatch'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(choices=[('waiting_material', 'Esperando material'), ('in_basket', 'En canasta'), ('in_process', 'En proceso'), ('finished', 'Terminado'), ('dispatched', 'Despachado')], default='waiting_material', max_length=20),
        ),
    ]
