# Generated by Django 4.2.30 on 2026-06-19 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0006_tubereception_batch_alter_productionbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrecord',
            name='qty_defective',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processrecord',
            name='qty_scrapped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processshiftentry',
            name='qty_defective',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReworkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_reworked', models.IntegerField(default=0, verbose_name='Piezas recuperadas')),
                ('qty_scrapped', models.IntegerField(default=0, verbose_name='Piezas descartadas (merma)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_entries', to=settings.AUTH_USER_MODEL)),
                ('process_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_entries', to='production.processrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
