# Generated by Django 4.2.30 on 2026-06-28 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_saw_rpm_to_tubespec(apps, schema_editor):
    """Best-effort: copia saw_type/rpm de cada producto a su tubo largo antes de borrarlos."""
    ProductType = apps.get_model('production', 'ProductType')
    for p in ProductType.objects.select_related('tube_spec').all():
        ts = p.tube_spec
        changed = False
        if getattr(p, 'saw_type', None) and getattr(p, 'saw_type') != 'none' and ts.saw_type == 'none':
            ts.saw_type = p.saw_type
            changed = True
        if getattr(p, 'rpm', None) and not ts.rpm:
            ts.rpm = p.rpm
            changed = True
        if changed:
            ts.save(update_fields=['saw_type', 'rpm'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0007_processrecord_qty_defective_and_more'),
    ]

    operations = [
        # 1) Agregar campos al tubo largo
        migrations.AddField(
            model_name='tubespec',
            name='rpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='RPM'),
        ),
        migrations.AddField(
            model_name='tubespec',
            name='saw_type',
            field=models.CharField(choices=[('hss', 'HSS'), ('tct', 'TCT'), ('none', 'Ninguno')], default='none', max_length=4, verbose_name='Tipo de sierra'),
        ),
        # 2) Copiar los valores existentes producto → tubo largo
        migrations.RunPython(copy_saw_rpm_to_tubespec, migrations.RunPython.noop),
        # 3) Borrar los campos del producto
        migrations.RemoveField(
            model_name='producttype',
            name='rpm',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='saw_type',
        ),
        migrations.AlterField(
            model_name='processrecord',
            name='shift',
            field=models.CharField(blank=True, choices=[('A', 'Turno 1 (06:00–14:00)'), ('B', 'Turno 2 (06:00–14:00)'), ('C', 'Turno 3 (14:00–22:00)'), ('D', 'Turno 5 (22:00–06:00)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='processshiftentry',
            name='shift',
            field=models.CharField(blank=True, choices=[('A', 'Turno 1 (06:00–14:00)'), ('B', 'Turno 2 (06:00–14:00)'), ('C', 'Turno 3 (14:00–22:00)'), ('D', 'Turno 5 (22:00–06:00)')], max_length=1),
        ),
        migrations.CreateModel(
            name='PackingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('estiba', 'Estiba'), ('caja', 'Caja / medio de manejo')], max_length=10)),
                ('quantity', models.IntegerField(verbose_name='Piezas en el medio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_dispatched', models.BooleanField(default=False)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_units', to='production.productionbatch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch', 'created_at'],
            },
        ),
    ]
