# Generated by Django 4.2.30 on 2026-07-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0008_remove_producttype_rpm_remove_producttype_saw_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuttingprogramline",
            name="pedido_quantity",
        ),
        migrations.AlterField(
            model_name="cuttingprogramline",
            name="total_quantity",
            field=models.IntegerField(verbose_name="Cantidad pedida (piezas)"),
        ),
    ]
