# Generated by Django 4.2.30 on 2026-07-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0009_remove_cuttingprogramline_pedido_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuttingprogramline",
            name="client",
            field=models.CharField(blank=True, max_length=200, verbose_name="Cliente"),
        ),
        migrations.AlterField(
            model_name="cuttingprogramline",
            name="saw_type",
            field=models.CharField(
                choices=[("hss", "HSS"), ("tct", "TCT")],
                default="hss",
                max_length=5,
                verbose_name="Tipo sierra",
            ),
        ),
    ]
