# Generated by Django 4.2.30 on 2026-07-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_cuttingprogramline_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='pieces_per_hour',
            field=models.FloatField(blank=True, null=True, verbose_name='Piezas/hora'),
        ),
        migrations.AlterField(
            model_name='tubespec',
            name='material',
            field=models.CharField(choices=[('cr', 'CR'), ('hr', 'HR'), ('cr_est', 'CR EST'), ('hr_est', 'HR EST'), ('gv', 'GV')], max_length=10),
        ),
    ]
