# Generated by Django 4.2.30 on 2026-07-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_producttype_pieces_per_hour_alter_tubespec_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='advance_high',
            field=models.FloatField(blank=True, null=True, verbose_name='Avance High'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='advance_low',
            field=models.FloatField(blank=True, null=True, verbose_name='Avance Low'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='packaging',
            field=models.CharField(blank=True, max_length=100, verbose_name='Embalaje'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='saw_teeth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de dientes'),
        ),
    ]
