# Generated by Django 4.2.30 on 2026-07-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_producttype_advance_high_producttype_advance_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubespec',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Item tubo largo'),
        ),
        migrations.AlterField(
            model_name='tubespec',
            name='material',
            field=models.CharField(choices=[('cr', 'CR'), ('hr', 'HR'), ('cr_est', 'CR EST'), ('hr_est', 'HR EST'), ('gv', 'GV'), ('ec', 'EC')], max_length=10),
        ),
    ]
